[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
cursor-core = { path = "crates/core" }
gif = "0.13"
tiny-skia = { version = "0.11", default-features = false, features = ["std", "simd"] }

[profile.dev]
opt-level = 2
